DROP DATABASE IF EXISTS tododb;
DROP USER IF EXISTS `todoadmin`@`%`;
DROP USER IF EXISTS `todouser`@`%`;
CREATE DATABASE IF NOT EXISTS tododb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `todoadmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `tododb`.* TO `todoadmin`@`%`;
CREATE USER IF NOT EXISTS `todouser`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `tododb`.* TO `todouser`@`%`;
FLUSH PRIVILEGES;